apiVersion: apps/v1
kind: Deployment
metadata:
  name: zocket-deployment
  namespace: zocket
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: aravindsuriya/zocket:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "postgres://myuser:mypassword@postgres-db:5432/mydatabase"
        - name: DJANGO_SETTINGS_MODULE
          value: "zocket.settings"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zocket-hpa
  namespace: zocket 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zocket-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
