apiVersion: apps/v1
kind: Deployment
metadata:
  name: zocket-deployment
  namespace: zocket
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: aravindsuriya/zocket:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DATABASE_URL
          value: "postgres://myuser:mypassword@postgres-db:5432/mydatabase"
        - name: DJANGO_SETTINGS_MODULE
          value: "zocket.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: zocket-service
  namespace: zocket
spec:
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
